### ISSUE TITLE
How to edit res/raw/*.xml?

### ISSUE THREAD

**Issue by arpruss** [robertosartori/SwypeRow#3]
What tools did you use to edit the res/raw/*.xml files? I tried axml2xml.pl and AxmlParserPy, and both crash and burn on these keyboard files.

**Comment by roberto-sartori-gl** [comment]
Well, i decompile Swype, edit xmls and recompile Swype. Then i extract the compiled files. It seems hard but after the first time you don't need to decompile, so...

**Comment by arpruss** [comment]
Would there be a way of having the build work with decompiled xml files instead, so that it would be easier to edit the xml files?

**Comment by roberto-sartori-gl** [comment]
Well, if you find a way, please tell me. I've tried a lot of thing (and i'm still trying), doing that would be much easier, but i didn't find a way.
- We can't replace that resources.
- We can't parse (and use) xml files as they are decompiled, because of references (like '@string\something').

-> We need compiled files.

**Comment by arpruss** [comment]
Do you decompile and recompile with apktool?

**Comment by roberto-sartori-gl** [comment]
Yes.
